-- ════════════════════════════════════════════════════════════════════
-- Nippon Hardware — MATERIAL MASTER v3.0  (KinLong supplier-aligned)
-- Source: Nippon_KinLong_Material_Master_FINAL.xlsx  ·  124 products
-- Generated: 2026-06-12
--
-- Full REPLACE: deletes every existing Nippon product, inserts the clean 124.
-- Dual coding:  model_no = ERP Model No · profile_code = KinLong Doc Code
-- Status + extra specs live in technical_specs jsonb (matchStatus, Length, …).
-- 8 Material Groups -> main_category (drives the registry category filter).
--
-- Safe to re-run. Run in Supabase SQL Editor.
-- ════════════════════════════════════════════════════════════════════

-- Guard: ensure all target columns exist (idempotent).
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model_no TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS profile_code TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS main_category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sub_category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS base_price NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS finish_color TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS material TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS direction TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tongue_length TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS spindle_length TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sub_description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS technical_specs JSONB DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_set BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;

BEGIN;

-- 1) Clear existing Nippon catalogue
DELETE FROM products WHERE company = 'Nippon';

-- 2) Insert clean 124-product master
INSERT INTO products (id, company, description, model_no, profile_code, brand, main_category, sub_category, category, unit, cost_price, base_price, finish_color, material, direction, tongue_length, spindle_length, sub_description, technical_specs, image_url, is_set, active) VALUES
  ('NIP-KL-CZS116AS-L54', 'Nippon', 'Casement Window Handle', 'CZS116AS-L54', 'CZS116AS', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 1376, 1376, 'Black', 'Aluminium alloy', NULL, NULL, NULL, 'Spring bolt length=54mm', '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS120A', 'Nippon', 'Casement Window Handle', 'CZS120A', 'CZS120A', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 1058, 1058, 'Black', 'Aluminium alloy', NULL, '55mm', NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS120AL55', 'Nippon', 'Casement Window Handle', 'CZS120AL55', 'CZS120AL55', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 0, 0, 'Black', 'Aluminium alloy', NULL, '55mm', NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS133-L55', 'Nippon', 'Casement Window Handle', 'CZS133-L55', 'CZS133', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 860, 860, 'Black / White', 'Aluminium alloy', NULL, '55mm', NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS160A-L55', 'Nippon', 'Casement Window Handle', 'CZS160A-L55', 'CZS160A', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 1161, 1161, 'Black / White', 'Aluminium alloy', NULL, '55mm', NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LCZS38-L24', 'Nippon', 'Casement Window Handle', 'LCZS38-L24', 'LCZS38', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 0, 0, 'Black', 'Aluminium alloy', NULL, '30mm', NULL, 'L=30mm', '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LCZS631-R-L55', 'Nippon', 'Casement Window Handle', 'LCZS631-R-L55', 'LCZS631', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 860, 860, 'Black', 'Aluminium alloy + Zinc alloy', 'Right / Left', '55mm', NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LCZS770', 'Nippon', 'Casement Window Handle', 'LCZS770', 'LCZS770', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 757, 757, 'Black', 'Aluminium alloy', 'Right / Left', NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LFZS20', 'Nippon', 'Casement Window Handle', 'LFZS20', 'LFZS20-L60', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 828, 828, 'Black', NULL, NULL, '60mm', NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS332-L55', 'Nippon', 'Casement Window Handle (Adjustable L/R)', 'CZS332-L55', 'CZS332', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 817, 817, 'Black', 'Aluminium alloy', 'Right (adjustable)', '55mm', NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LCZS631-L-L55', 'Nippon', 'Handle', 'LCZS631-L-L55', 'LCZS631', 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 860, 860, NULL, 'Aluminium alloy+Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-UP-FZS1043A', 'Nippon', 'Handle', 'UP-FZS1043A', NULL, 'KIN LONG', 'Handles', 'Window Handle', 'Hardware', 'PCS', 1279, 1279, 'Black', NULL, 'Left', NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-MZS208C', 'Nippon', 'Door Handle', 'MZS208C', 'MZS208C', 'KIN LONG', 'Handles', 'Door Handle', 'Hardware', 'PCS', 1376, 1376, 'Black / White', 'Aluminium alloy', 'Right', NULL, NULL, 'Square steel 8x8x100mm; Screw M5x75mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-MZS220C', 'Nippon', 'Door Handle', 'MZS220C', 'MZS220C', 'KIN LONG', 'Handles', 'Door Handle', 'Hardware', 'PCS', 1269, 1269, 'Black', 'Aluminium alloy', 'Right', NULL, NULL, 'Square steel 8x8x100mm; Screw M5x75mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-MZS3208C', 'Nippon', 'Door Handle', 'MZS3208C', 'MZS3208C', 'KIN LONG', 'Handles', 'Door Handle', 'Hardware', 'PCS', 1376, 1376, 'Black', 'Aluminium alloy', 'Right', NULL, NULL, 'Square steel 8x8x100mm; Screw M5x75mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-Z201-L100', 'Nippon', 'Lift & Slide Door Handle', 'Z201-L100', 'Z201', 'KIN LONG', 'Handles', 'Door Handle', 'Hardware', 'PCS', 3655, 3655, 'Black / White', 'Aluminium alloy', NULL, NULL, NULL, 'Square steel 10x10x100mm; Screw M5x70mm', '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-Z202', 'Nippon', 'Lift & Slide Door Handle', 'Z202', 'Z202', 'KIN LONG', 'Handles', 'Door Handle', 'Hardware', 'PCS', 5850, 5850, 'Black', 'Zinc alloy', NULL, NULL, NULL, 'Square steel 10x10x100mm; Screw M5x70mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZTS218', 'Nippon', 'Metro Handle (Sliding)', 'ZTS218', 'ZTS218', 'KIN LONG', 'Handles', 'Door Handle', 'Hardware', 'PCS', 3139, 3139, 'Black', 'Zinc alloy', NULL, '31mm', NULL, 'Single-side; fork tongue 31mm; stroke 20mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-UP-FZS140', 'Nippon', 'Child Safety Window Handle', 'UP-FZS140', 'UP-FZS140-L55', 'KIN LONG', 'Handles', 'Child-Safety Handle', 'Hardware', 'PCS', 1110, 1110, 'Black', NULL, NULL, NULL, '60mm', 'Spindle length=60mm', '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-J5C-R', 'Nippon', 'HINGE', 'J5C-R', NULL, 'KIN LONG', 'Hinges & Stays', 'Window Hinge', 'Hardware', 'PCS', 1144, 2000, 'Black', 'Aluminium profile', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-MJ35-L', 'Nippon', 'Hinge', 'T-MJ35-L', NULL, 'KIN LONG', 'Hinges & Stays', 'Window Hinge', 'Hardware', 'PCS', 1548, 1548, 'White', 'Aluminium profile', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-MJ35-R', 'Nippon', 'Hinge', 'T-MJ35-R', NULL, 'KIN LONG', 'Hinges & Stays', 'Window Hinge', 'Hardware', 'PCS', 1548, 1548, 'White', 'Aluminium profile', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-LCJ13', 'Nippon', 'Casement Window Hinge (C-Groove)', 'LCJ13', 'LCJ13', 'KIN LONG', 'Hinges & Stays', 'Window Hinge', 'Hardware', 'PCS', 520, 520, 'Black / White', 'Aluminium profile', NULL, NULL, NULL, 'C groove; narrow frame; gap 3.5-5.0mm', '{"matchStatus": "Exact Match", "Load Bearing": "55kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-NDHB10BR', 'Nippon', 'Inward T&T Window Hinge - Lower', 'NDHB10BR', 'NDHB10B', 'KIN LONG', 'Hinges & Stays', 'Window Hinge', 'Hardware', 'PCS', 0, 0, 'Black', 'Aluminium profile + Zinc alloy', 'Right', NULL, NULL, NULL, '{"matchStatus": "Near-Match", "Load Bearing": "90kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-NDHA10A', 'Nippon', 'Inward T&T Window Hinge - Upper', 'NDHA10A', 'NDHA10A', 'KIN LONG', 'Hinges & Stays', 'Window Hinge', 'Hardware', 'PCS', 0, 0, 'Black', 'Aluminium profile + Zinc alloy', 'Right', NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Load Bearing": "90kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-HCC40A-14', 'Nippon', 'Friction Stay (C-Groove)', 'HCC40A-14', 'HCC40A14', 'KIN LONG', 'Hinges & Stays', 'Friction Stay', 'Hardware', 'PCS', 0, 0, 'Natural', 'SS304', NULL, NULL, NULL, 'C-groove; H<1600; W<600; 90°', '{"matchStatus": "Near-Match", "Length": "365mm", "Load Bearing": "34kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-HCC40A-16', 'Nippon', 'Friction Stay (C-Groove)', 'HCC40A-16', 'HCC40A16', 'KIN LONG', 'Hinges & Stays', 'Friction Stay', 'Hardware', 'PCS', 0, 0, 'Natural', 'SS304', NULL, NULL, NULL, 'C-groove; H<1700; W<700; 90°', '{"matchStatus": "Near-Match", "Length": "416mm", "Load Bearing": "39kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-HC320-16', 'Nippon', 'Friction Stay (No-Groove)', 'HC320-16', 'HC320-16', 'KIN LONG', 'Hinges & Stays', 'Friction Stay', 'Hardware', 'PCS', 989, 989, 'Natural', 'SS304', NULL, NULL, NULL, 'No groove; H<1500; W<750; 90°', '{"matchStatus": "Exact Match", "Length": "413mm", "Load Bearing": "36kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-HC320-18', 'Nippon', 'Friction Stay (No-Groove)', 'HC320-18', 'HC320-18', 'KIN LONG', 'Hinges & Stays', 'Friction Stay', 'Hardware', 'PCS', 1084, 1084, 'Natural', 'SS304', NULL, NULL, NULL, 'No groove; H<1500; W<800; 90°', '{"matchStatus": "Exact Match", "Length": "458mm", "Load Bearing": "38kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-HCC40A-12', 'Nippon', 'Friction Stay (C-Groove)', 'HCC40A-12', 'HCC40A12', 'KIN LONG', 'Hinges & Stays', 'Friction Stay', 'Hardware', 'PCS', 0, 0, 'Natural', 'SS304', NULL, NULL, NULL, 'C-groove; H<1500; W<500; 90°', '{"matchStatus": "Near-Match", "Length": "313mm", "Load Bearing": "30kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-J5C', 'Nippon', 'Pivot Hinge (Casement Door)', 'J5C', 'J5C', 'KIN LONG', 'Hinges & Stays', 'Pivot Hinge', 'Hardware', 'PCS', 1144, 1144, 'Black / White', 'Aluminium + Stainless steel', 'Right / Left', NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Load Bearing": "110kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-MJ35', 'Nippon', 'Pivot Hinge (Heavy Duty)', 'T-MJ35', 'T-MJ35', 'KIN LONG', 'Hinges & Stays', 'Pivot Hinge', 'Hardware', 'PCS', 1548, 1548, 'Black / White', 'Aluminium + Stainless steel', 'Right / Left', NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Load Bearing": "150kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-LYHDX40B-R', 'Nippon', 'Outward T&T Bottom Pivot Hinge', 'LYHDX40B-R', 'LYHDX40B', 'KIN LONG', 'Hinges & Stays', 'Pivot Hinge', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel + Zinc alloy', 'Right', NULL, NULL, NULL, '{"matchStatus": "Near-Match", "Load Bearing": "70kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-LYHPS40A', 'Nippon', 'Outward T&T Upper Pivot Hinge', 'LYHPS40A', 'LYHPS40A', 'KIN LONG', 'Hinges & Stays', 'Pivot Hinge', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel + Zinc alloy', 'Right', NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Load Bearing": "70kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-FC500-12', 'Nippon', 'Pegstay', 'FC500-12', 'FC500-12', 'KIN LONG', 'Hinges & Stays', 'Pegstay', 'Hardware', 'PCS', 373, 373, 'Natural', 'SS304', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "304mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-FC500-14', 'Nippon', 'Pegstay', 'FC500-14', 'FC500-14', 'KIN LONG', 'Hinges & Stays', 'Pegstay', 'Hardware', 'PCS', 424, 424, 'Natural', 'SS304', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "355mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-SC200-10', 'Nippon', 'Pegstay', 'SC200-10', 'SC200-10', 'KIN LONG', 'Hinges & Stays', 'Pegstay', 'Hardware', 'PCS', 375, 375, 'Natural', 'SS304', 'Left / Right', NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "254mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-SC200-12', 'Nippon', 'Pegstay', 'SC200-12', 'SC200-12/I', 'KIN LONG', 'Hinges & Stays', 'Pegstay', 'Hardware', 'PCS', 439, 439, 'Natural', 'SS304', 'Left / Right', NULL, NULL, NULL, '{"matchStatus": "Near-Match", "Length": "305mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-LZA4', 'Nippon', 'Corner Device', 'LZA4', 'LZA4', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LZB5', 'Nippon', 'Corner Device', 'LZB5', 'LZB5', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZA1', 'Nippon', 'Corner Device', 'ZA1', 'ZA1', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-SK29', 'Nippon', 'Locking Plate', 'SK29', 'SK29', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-SK51', 'Nippon', 'Locking Plate', 'SK51', 'SK51', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 559, 559, NULL, 'Aluminium', NULL, NULL, NULL, 'W=10.5mm; H=29.5mm', '{"matchStatus": "Exact Match", "Length": "37mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-TLK-11A', 'Nippon', 'Locking Plate', 'TLK-11A', 'TLK-11A', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZA1-6A', 'Nippon', 'Locking Plate', 'ZA1-6A', 'ZA1-6A', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-KMB180A', 'Nippon', 'Lock Plate / Cover Plate', 'KMB180A', 'KMB180A', 'KIN LONG', 'Locking System', 'Locking Plate', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, 'W=21mm', '{"matchStatus": "Exact Match", "Length": "181mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-JMSC26/II', 'Nippon', 'Door Lock Body', 'JMSC26/II', 'JMSC26/II', 'KIN LONG', 'Locking System', 'Door Lock Body', 'Hardware', 'PCS', 1909, 1909, NULL, 'Zinc alloy + Stainless steel', NULL, NULL, NULL, 'Center distance=26mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-JMSC28/I', 'Nippon', 'Door Lock Body', 'JMSC28/I', 'JMSC28/I', 'KIN LONG', 'Locking System', 'Door Lock Body', 'Hardware', 'PCS', 2231, 2231, NULL, 'Zinc alloy + Stainless steel', NULL, NULL, NULL, 'Center distance=28mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-JMSD35/I', 'Nippon', 'Door Lock Body', 'T-JMSD35/I', 'T-JMSD35/I', 'KIN LONG', 'Locking System', 'Door Lock Body', 'Hardware', 'PCS', 2691, 2691, NULL, 'Zinc alloy + Stainless steel', NULL, NULL, NULL, 'Center distance=35mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-MSD35/I', 'Nippon', 'Door Lock Body', 'T-MSD35/I', 'T-MSD35/I', 'KIN LONG', 'Locking System', 'Door Lock Body', 'Hardware', 'PCS', 2365, 2365, NULL, 'Zinc alloy + Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "396.5mm", "Backset": "35mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-TMSD35/II', 'Nippon', 'Door Lock Body', 'TMSD35/II', 'TMSD35/II', 'KIN LONG', 'Locking System', 'Door Lock Body', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy + Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "330mm", "Backset": "35mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-MSD35/II', 'Nippon', 'door lock', 'T-MSD35/II', NULL, 'KIN LONG', 'Locking System', 'Door Lock Body', 'Hardware', 'PCS', 2064, 2064, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZCD75X25', 'Nippon', 'Main Transmission Rod', 'ZCD75X25', 'ZCD75X25', 'KIN LONG', 'Locking System', 'Transmission Rod', 'Hardware', 'PCS', 224, 224, NULL, 'Stainless steel + Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Pin Length": "25mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZCD75X40', 'Nippon', 'Main Transmission Rod', 'ZCD75X40', 'ZCD75X40', 'KIN LONG', 'Locking System', 'Transmission Rod', 'Hardware', 'PCS', 245, 245, NULL, 'Stainless steel + Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Pin Length": "40mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-N36A', 'Nippon', 'Middle Transmission Rod', 'N36A', 'N36A', 'KIN LONG', 'Locking System', 'Transmission Rod', 'Hardware', 'PCS', 258, 258, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-N37A', 'Nippon', 'Side Transmission Rod', 'N37A', 'N37A', 'KIN LONG', 'Locking System', 'Transmission Rod', 'Hardware', 'PCS', 172, 172, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-N39', 'Nippon', 'Side Transmission Rod', 'N39', 'N39', 'KIN LONG', 'Locking System', 'Transmission Rod', 'Hardware', 'PCS', 138, 138, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZCD08X54.5', 'Nippon', 'Connect Pin', 'ZCD08X54.5', 'ZCD08X54.5', 'KIN LONG', 'Locking System', 'Connecting Rod', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, '50mm exposed after install', '{"matchStatus": "Exact Match", "Length": "54.5mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-H52-10-100', 'Nippon', 'Connecting Rod', 'H52-10-100', 'H52-10-100', 'KIN LONG', 'Locking System', 'Connecting Rod', 'Hardware', 'PCS', 602, 602, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "100mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZCD-08X54.5', 'Nippon', 'Linking Rod', 'ZCD-08X54.5', NULL, 'KIN LONG', 'Locking System', 'Connecting Rod', 'Hardware', 'PCS', 108, 108, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-LDG-194(HW)', 'Nippon', 'Polyamide Insulation Connecting Rod', 'LDG-194(HW)', 'LDG-194', 'KIN LONG', 'Locking System', 'Connecting Rod', 'Hardware', 'PCS', 0, 0, NULL, 'PA66GF25', NULL, NULL, NULL, 'Used with ZCD-08 & HDS8', '{"matchStatus": "Near-Match", "Length": "250LM/Roll"}'::jsonb, NULL, false, true),
  ('NIP-KL-XCDQ24030', 'Nippon', 'Transmitter', 'XCDQ24030', 'XCDQ24030', 'KIN LONG', 'Locking System', 'Transmitter', 'Hardware', 'PCS', 900, 900, 'Silver / Natural', NULL, NULL, NULL, NULL, 'Center distance=30mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-ZDA120AT', 'Nippon', 'Transmitter (Adjustable)', 'ZDA120AT', 'ZDA120AT', 'KIN LONG', 'Locking System', 'Transmitter', 'Hardware', 'PCS', 1311, 1311, 'Black', 'CIFIAL', NULL, NULL, NULL, 'Center distance=25-32mm adj', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CDG2370A', 'Nippon', 'Transmitter Lock', 'CDG2370A', 'CDG2370A', 'KIN LONG', 'Locking System', 'Transmitter', 'Hardware', 'PCS', 9245, 9245, NULL, 'Q235B + Aluminium', NULL, NULL, NULL, 'W=20.6mm; H=52mm', '{"matchStatus": "Exact Match", "Length": "2370mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-KIL2857/T', 'Nippon', 'Door Cylinder', 'KIL2857/T', 'KIL2857/T', 'KIN LONG', 'Locking System', 'Lock Cylinder', 'Hardware', 'PCS', 0, 0, NULL, 'Brass', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "85mm (28+57)"}'::jsonb, NULL, false, true),
  ('NIP-KL-KIL3247', 'Nippon', 'Door Cylinder (Key Both Sides)', 'KIL3247', 'KIL3247', 'KIN LONG', 'Locking System', 'Lock Cylinder', 'Hardware', 'PCS', 1954, 1954, NULL, 'Brass', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "79mm (32+47)"}'::jsonb, NULL, false, true),
  ('NIP-KL-HDS8', 'Nippon', 'Active Lock Point', 'HDS8', 'HDS8', 'KIN LONG', 'Locking System', 'Lock Point', 'Hardware', 'PCS', 65, 65, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-MCX320A', 'Nippon', 'Door Socket', 'MCX320A', 'MCX320A', 'KIN LONG', 'Locking System', 'Lock Point', 'Hardware', 'PCS', 610, 610, NULL, 'Zinc alloy + Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "300mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-CDG2370-06G19.5', 'Nippon', 'Supporting Socket / Seat', 'CDG2370-06G19.5', 'CDG2370-06', 'KIN LONG', 'Locking System', 'Socket', 'Hardware', 'PCS', 0, 0, NULL, 'Aluminium profile', NULL, NULL, NULL, 'G=19.5mm', '{"matchStatus": "Near-Match", "Length": "111.5mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-LCDG41', 'Nippon', 'Intermediate Drive Lever', 'LCDG41', 'LCDG41', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LN57', 'Nippon', 'Anti-Drop Device', 'LN57', 'LN57', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LPX14A-16', 'Nippon', 'Hardware', 'LPX14A-16', NULL, 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-LPX14A16', 'Nippon', 'Limiter', 'LPX14A16', 'LPX14A16', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, 'Window width >650mm; open angle 0-90°', '{"matchStatus": "Exact Match", "Length": "441mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-LPX30A', 'Nippon', 'Limiter', 'LPX30A', 'LPX30A', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-FSP10', 'Nippon', 'Loose Preventer', 'FSP10', 'FSP10', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-FWG10A', 'Nippon', 'Misuse Preventer', 'FWG10A', 'FWG10A', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LN56', 'Nippon', 'Overturn Supporter', 'LN56', 'LN56', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-AQS10', 'Nippon', 'Safety Device', 'AQS10', 'AQS10', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Aluminium alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LN54', 'Nippon', 'Supporting Block', 'LN54', 'LN54', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LZCK05', 'Nippon', 'Supporting Block', 'LZCK05', 'LZCK05', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-FSG-01', 'Nippon', 'Waterproof Cap', 'FSG-01', 'FSG-01', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-N50', 'Nippon', 'Overturn Supporter', 'N50', 'N50', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-N31', 'Nippon', 'Preventer', 'N31', 'N31', 'KIN LONG', 'Sliding & Lift System', 'Lift & Slide Accessory', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-TLS12-6', 'Nippon', 'Lock hook', 'TLS12-6', NULL, 'KIN LONG', 'Sliding & Lift System', 'Sliding Lock', 'Hardware', 'PCS', 0, 0, NULL, '304', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-TLS22-6', 'Nippon', 'lock hook', 'TLS22-6', NULL, 'KIN LONG', 'Sliding & Lift System', 'Sliding Lock', 'Hardware', 'PCS', 75, 75, NULL, '304', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-TLS21HS', 'Nippon', 'Sliding Window Lock with Hook', 'TLS21HS', 'TLS21HS', 'KIN LONG', 'Sliding & Lift System', 'Sliding Lock', 'Hardware', 'PCS', 1269, 1269, 'Black', 'Zinc alloy + Stainless steel', NULL, NULL, NULL, 'TLS12-6; Screw M5x35mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-TLS22HS', 'Nippon', 'Sliding Window Lock with Hook', 'TLS22HS', 'TLS22HS', 'KIN LONG', 'Sliding & Lift System', 'Sliding Lock', 'Hardware', 'PCS', 796, 796, 'Black', 'Aluminium alloy + Stainless steel', NULL, NULL, NULL, 'TLS22-6; Screw M5x35mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-TLS32', 'Nippon', 'Sliding Window Lock with Hook', 'TLS32', 'TLS32', 'KIN LONG', 'Sliding & Lift System', 'Sliding Lock', 'Hardware', 'PCS', 0, 0, 'Black', 'Aluminium alloy + Stainless steel', NULL, NULL, NULL, 'TLS22-6; Screw M5x35mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-H52A', 'Nippon', 'Back Roller (Lift & Slide)', 'H52A', 'H52A', 'KIN LONG', 'Sliding & Lift System', 'Roller / Wheel', 'Hardware', 'PCS', 3010, 3010, NULL, 'Zinc alloy', NULL, NULL, NULL, 'Add middle roller if sash >2000mm', '{"matchStatus": "Exact Match", "Length": "275mm", "Load Bearing": "300kg"}'::jsonb, NULL, false, true),
  ('NIP-KL-H50-20A', 'Nippon', 'Cushion / Pad Block', 'H50-20A', 'H50-20A', 'KIN LONG', 'Sliding & Lift System', 'Roller / Wheel', 'Hardware', 'PCS', 86, 86, 'Black', 'TPR 7005A', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CML35G19K19.2A', 'Nippon', 'Double Roller', 'CML35G19K19.2A', 'CML35G19K19.2A', 'KIN LONG', 'Sliding & Lift System', 'Roller / Wheel', 'Hardware', 'PCS', 327, 327, NULL, 'Carbon steel + wear-resistant plastic', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Load Bearing": "80kg/2pcs"}'::jsonb, NULL, false, true),
  ('NIP-KL-H50B', 'Nippon', 'Front Roller (Lift & Slide)', 'H50B', 'H50B', 'KIN LONG', 'Sliding & Lift System', 'Roller / Wheel', 'Hardware', 'PCS', 5160, 5160, NULL, 'Zinc alloy + SS304 + plastic', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "377mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-BT-4x05x50m', 'Nippon', 'Butyl Tape', 'BT-4x05x50m', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, NULL, 'Butyl', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-GB-5x8x3m-DG', 'Nippon', 'Georgian Bar', 'GB-5x8x3m-DG', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, 'Dark Gold', 'PVC', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-GB-5x8x3m-W', 'Nippon', 'Georgian Bar', 'GB-5x8x3m-W', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, 'White', 'PVC', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-P0301', 'Nippon', 'Georgian Flower', 'P0301', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, 'Dark Gold', 'PVC', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-P0401', 'Nippon', 'Georgian Flower', 'P0401', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, 'Dark Gold', 'PVC', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-P0401-W', 'Nippon', 'Georgian Flower', 'P0401-W', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, 'White', 'PVC', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-P0801', 'Nippon', 'Georgian Flower', 'P0801', NULL, 'Soleron', 'Profiles & Point-Fixing', 'Profile / Bar', 'Hardware', 'PCS', 0, 0, 'Dark Gold', 'PVC', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-T-FK-D', 'Nippon', 'Anti-Strike Block', 'T-FK-D', 'T-FK-D', 'KIN LONG', 'Profiles & Point-Fixing', 'Supporting / Strike Block', 'Hardware', 'PCS', 65, 65, NULL, 'Polyamide + rubber', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-H52-12', 'Nippon', 'Supporting Block', 'H52-12', 'H52-12', 'KIN LONG', 'Profiles & Point-Fixing', 'Supporting / Strike Block', 'Hardware', 'PCS', 65, 65, NULL, '3017', NULL, NULL, NULL, 'W=26.2mm; H=23.8mm', '{"matchStatus": "Exact Match", "Length": "46.5mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-CDG2370-05G23', 'Nippon', 'Supporting Block (Back-up Block)', 'CDG2370-05G23', 'CDG2370-05', 'KIN LONG', 'Profiles & Point-Fixing', 'Supporting / Strike Block', 'Hardware', 'PCS', 0, 0, NULL, 'Aluminium profile', NULL, NULL, NULL, 'W=21.6mm; G=23mm', '{"matchStatus": "Near-Match", "Length": "28mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-H52-13', 'Nippon', 'Water Cap', 'H52-13', 'H52-13', 'KIN LONG', 'Profiles & Point-Fixing', 'Supporting / Strike Block', 'Hardware', 'PCS', 43, 43, NULL, '3017', NULL, NULL, NULL, 'W=9.4mm; H=8.8mm', '{"matchStatus": "Exact Match", "Length": "60mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-N33A', 'Nippon', 'Cushion Block', 'N33A', 'N33A', 'KIN LONG', 'Profiles & Point-Fixing', 'Supporting / Strike Block', 'Hardware', 'PCS', 0, 0, NULL, 'Zinc alloy', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS100-06C-34', 'Nippon', 'Hardware', 'CZS100-06C-34', NULL, 'KIN LONG', 'Profiles & Point-Fixing', 'Other', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-CZS631-06-34', 'Nippon', 'Hardware', 'CZS631-06-34', NULL, 'KIN LONG', 'Profiles & Point-Fixing', 'Other', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-LYHPS40B-R', 'Nippon', 'Hardware', 'LYHPS40B-R', NULL, 'KIN LONG', 'Profiles & Point-Fixing', 'Other', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-NDHA10BR', 'Nippon', 'Hardware', 'NDHA10BR', NULL, 'KIN LONG', 'Profiles & Point-Fixing', 'Other', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-Z15', 'Nippon', 'Connector', 'Z15', 'Z15', 'KIN LONG', 'Profiles & Point-Fixing', 'Routel / Connector', 'Hardware', 'PCS', 2050, 2050, 'Natural + colour zinc plating', 'SS304 / Q235B', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match", "Length": "70mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-ATF11X', 'Nippon', 'Routel', 'ATF11X', 'ATF11X', 'KIN LONG', 'Profiles & Point-Fixing', 'Routel / Connector', 'Hardware', 'PCS', 1450, 1450, 'Natural', 'SS304', NULL, NULL, NULL, 'Aluminium sleeve & shims incl; T=8-10mm', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LG11A', 'Nippon', 'Small Connector Rod', 'LG11A', 'LG11', 'KIN LONG', 'Profiles & Point-Fixing', 'Routel / Connector', 'Hardware', 'PCS', 0, 0, NULL, 'Stainless steel', NULL, NULL, NULL, NULL, '{"matchStatus": "Near-Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-A250A1', 'Nippon', '1-Way Long Spider Fitting', 'A250A1', 'A250A1', 'KIN LONG', 'Profiles & Point-Fixing', 'Spider Fitting', 'Hardware', 'PCS', 1900, 1900, 'Satin', 'CF8', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-A250A2', 'Nippon', '2-Way Spider Fitting (90°)', 'A250A2', 'A250A2', 'KIN LONG', 'Profiles & Point-Fixing', 'Spider Fitting', 'Hardware', 'PCS', 2750, 2750, 'Satin', 'CF8', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-A250A4', 'Nippon', '4-Way Spider Fitting', 'A250A4', 'A250A4', 'KIN LONG', 'Profiles & Point-Fixing', 'Spider Fitting', 'Hardware', 'PCS', 4950, 4950, 'Satin', 'CF8', NULL, NULL, NULL, NULL, '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-KL-WS601', 'Nippon', 'Neutral Silicone Sealant (Weatherproof)', 'KL-WS601', 'KL-WS601', 'KIN LONG', 'Sealants', 'Silicone Sealant', 'Hardware', 'PCS', 727, 727, 'Black', 'Silicone', NULL, NULL, NULL, '100% Neutral; 20pcs/carton; shelf life 12 months', '{"matchStatus": "Exact Match", "Length": "590ml Sausage"}'::jsonb, NULL, false, true),
  ('NIP-KL-SV888', 'Nippon', 'Weatherproof Silicone', 'SV888', NULL, 'SIWAY', 'Sealants', 'Silicone Sealant', 'Hardware', 'PCS', 0, 0, 'White', 'Silicone', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-H-102', 'Nippon', 'Non-digging Floor Spring', 'H-102', NULL, 'HuangXing', 'Door Closing', 'Floor Spring', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-KPF-20', 'Nippon', 'Top Patch', 'KPF-20', NULL, 'HuangXing', 'Door Closing', 'Floor Spring', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-M5X10', 'Nippon', 'Countersunk Screw (for J5C)', 'M5X10', 'M5X10', 'KIN LONG', 'Fasteners & Consumables', 'Screw / Fastener', 'Hardware', 'PCS', 0, 0, NULL, 'Steel', NULL, NULL, NULL, 'Phillips head; for J5C', '{"matchStatus": "Exact Match", "Length": "M5x10mm"}'::jsonb, NULL, false, true),
  ('NIP-KL-J5-7', 'Nippon', 'Fan Clamping Block (for J5C)', 'J5-7', 'J5-7', 'KIN LONG', 'Fasteners & Consumables', 'Screw / Fastener', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, 'For door hinge J5C', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-J5-8', 'Nippon', 'Frame Clamping Block (for J5C)', 'J5-8', 'J5-8', 'KIN LONG', 'Fasteners & Consumables', 'Screw / Fastener', 'Hardware', 'PCS', 0, 0, NULL, NULL, NULL, NULL, NULL, 'For door hinge J5C', '{"matchStatus": "Exact Match"}'::jsonb, NULL, false, true),
  ('NIP-KL-LD-02-35', 'Nippon', 'Screw', 'LD-02-35', NULL, 'KIN LONG', 'Fasteners & Consumables', 'Screw / Fastener', 'Hardware', 'PCS', 0, 0, NULL, 'Steel', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-M5X75', 'Nippon', 'Screws', 'M5X75', NULL, 'KIN LONG', 'Fasteners & Consumables', 'Screw / Fastener', 'Hardware', 'PCS', 25, 25, NULL, '304', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true),
  ('NIP-KL-LMS003-100', 'Nippon', 'Square steel', 'LMS003-100', NULL, 'KIN LONG', 'Fasteners & Consumables', 'Screw / Fastener', 'Hardware', 'PCS', 150, 150, NULL, 'Carbon steel', NULL, NULL, NULL, NULL, '{"matchStatus": "ERP Only"}'::jsonb, NULL, false, true);

COMMIT;

-- Verify: SELECT main_category, count(*) FROM products WHERE company='Nippon' GROUP BY 1 ORDER BY 2 DESC;
